
# a = 1
# while a <= 10:
#     print("1 x",a,"=", a*1)
#     a+=1
# a = 1
# while a <= 10:
#     print("2 x",a,"=", a*2)
#     a+=1
# a = 1
# while a <= 10:
#     print("3 x",a,"=", a*3)
#     a+=1
# a = 1
# while a <= 10:
#     print("4 x",a,"=", a*4)
#     a+=1
# a = 1
# while a <= 10:
#     print("5 x",a,"=", a*5)
#     a+=1
# a = 1
# while a <= 10:
#     print("6 x",a,"=", a*6)
#     a+=1
# a = 1
# while a <= 10:
#     print("7 x",a,"=", a*7)
#     a+=1
# a = 1
# while a <= 10:
#     print("8 x",a,"=", a*8)
#     a+=1
# a = 1
# while a <= 10:
#     print("9 x",a,"=", a*9)
#     a+=1
# a = 1
# while a <= 10:
#     print("10 x",a,"=", a*10)
#     a+=1